- hosts: all
  tasks:
    
    - name: "APT Update"
      become: yes
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400

        
    - name: "Instala pacotes em lote"
      apt:
        name: "{{ item }}"
        state: latest
      become: yes # roda com sudo
      with_items:
        - php7.4
        - apache2
        - libapache2-mod-php7.4
        - php-mysql
        - php-curl
        - mysql-server
        - python3-pycurl
        - python3-mysqldb
        - unzip

    - shell: mysql --version
      register: ps
    - debug:
        msg: "Verifica instalação: '{{ ps.stdout_lines }}' "
        
    - name: "Fazendo downlaod do wordpress"
      get_url:
        url: "https://br.wordpress.org/latest-pt_BR.tar.gz"
        dest: "/tmp/wordpress.tar.gz"

    - shell: ls -la /tmp/wordpress.tar.gz
      register: ps
    - debug:
        msg: "Verifica se fez o download: '{{ ps.stdout_lines }}' "
        
    - name: "Fazendo descompactação dos arquivos do WP"
      unarchive:
        src: "/tmp/wordpress.tar.gz"
        dest: "/var/www"
        remote_src: yes
      become: yes

    - shell: ls -la /var/www/wordpress
      register: ps
    - debug:
        msg: " '{{ ps.stdout_lines }}' "
        
        
    - name: "Copia arquivo WP"
      copy:
        src: '/var/www/wordpress/wp-config-sample.php'
        dest: '/var/www/wordpress/wp-config.php'
        remote_src: yes
      become: yes

    - shell: ls -la /var/www/wordpress
      register: ps
    - debug:
        msg: " '{{ ps.stdout_lines }}' "
        
        
        
        
